title: "SoCcer Manager"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2526S2-CS2103-F08-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
